### ISSUE TITLE
pairing check fails on smartpy but succeeds on edo2net

### ISSUE THREAD

**Issue by DariusParvin** [RomarQ/tezos-bls12-381#1]
I have generated a smart contract using SmartPy that uses `sp.pairing_check`. When I test it within the scenario it fails, but when I test it on edo2net it succeeds. On edo2net I'm using the same contracts and same inputs. 

The entrypoint which uses the pairing check is `custClose`. That triggers a contract call to another contract (`PSSigContract`) which does the pairing check. 

[Here](https://pastebin.com/n32ZtiXi) is the smartpy code with the scripts and scenario.

And [here](https://arronax.io/tezos/edonet/operations/onxcT9aNH3kgS9AXtkuAv61FAY6R81X3poXL5hEZRXTLnRMvQvw) is the operation happening on chain which is successful, ie the pairing check succeeds.

**Comment by RomarQ** [comment]
Fixed in commit 56331d238c94cdc98a5addbcd7380c2dabcc3a72

Thanks for the report :+1:
